version: '3'
services:
   db:
     image: mongo:latest
   membership:
     build: .
     depends_on:
       - db
       - mailcatcher
     ports:
       - "3001:3001"
       - "3002:3002"
   mailcatcher:
     image: ministryofjustice/mailcatcher
     ports:
       - "1080:1080"
   proxy:
     image: nginx
     build: ./nginx/
     ports:
       - "8080:8080"
     depends_on:
       - membership
