<form method="post" action="/login">
	<p></p>
	<p>
		<label for="email">Email: </label>
		<input id="email" name="email" type="text" class="form-control" />
	</p>
	<p>
		<label for="password">Password: </label>
		<input id="password" name="password" type="password" class="form-control" />
	</p>
	<p>
		<button class="btn btn-block btn-lg btn-primary" role="button">Login</button>
		<a class="btn btn-block btn-sm btn-default" href="/password-reset">Forgotten your password?</a>
	</p>
</form>
